In [1]:
import pandas as pd

In [2]:
db = pd.read_excel("dataset.xlsx","Course list",index_col=0)

In [3]:
db.head()

,Title,Length,Priority,Available blocks,Unavailable blocks,Minimum section size,Target section size,Maximum section size,Number of sections,Total credits
Course code,,,,,,,,,,
ARTBND,Band - High,2.0,Core course,"1A, 1B, 2A, 2B, 3, 4A, 4B",NaN,7,25,40,1,1.0
ARTChor,Chorus - High,2.0,Core course,"1A, 1B, 2A, 2B, 3, 4A, 4B",NaN,7,20,40,1,1.0
ARTDRAW,Drawing and Painting,2.0,Core course,"1A, 1B, 2A, 2B, 3, 4A, 4B",NaN,7,15,26,1,1.0
ARTSTD1,Studio Art I,1.0,Core course,"1A, 1B, 2A, 2B, 3, 4A, 4B",NaN,7,15,26,1,0.5
ARTSTD2,Studio Art II,1.0,Core course,"1A, 1B, 2A, 2B, 3, 4A, 4B",NaN,7,15,26,1,0.5

In [8]:
db.index = db.index.map(lambda x: x.upper())

In [9]:
db.head()

,Title,Length,Priority,Available blocks,Unavailable blocks,Minimum section size,Target section size,Maximum section size,Number of sections,Total credits
Course code,,,,,,,,,,
ARTBND,Band - High,2.0,Core course,"1A, 1B, 2A, 2B, 3, 4A, 4B",NaN,7,25,40,1,1.0
ARTCHOR,Chorus - High,2.0,Core course,"1A, 1B, 2A, 2B, 3, 4A, 4B",NaN,7,20,40,1,1.0
ARTDRAW,Drawing and Painting,2.0,Core course,"1A, 1B, 2A, 2B, 3, 4A, 4B",NaN,7,15,26,1,1.0
ARTSTD1,Studio Art I,1.0,Core course,"1A, 1B, 2A, 2B, 3, 4A, 4B",NaN,7,15,26,1,0.5
ARTSTD2,Studio Art II,1.0,Core course,"1A, 1B, 2A, 2B, 3, 4A, 4B",NaN,7,15,26,1,0.5

In [10]:
db.to_json("course_list.json",orient="index",indent=4)